[package]
name = "srt-translate"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
dify-client = "0.3.1"
env_logger = "0.11.5"
indicatif = "0.17.8"
log = "0.4.22"
srtlib = "0.2.0"
tokio = { version = "1.41.0", features = ["full"] }
